name: seahorse
channels:
  - defaults
dependencies:
  - python=3.6.5
  - pip=10.0.1
  - pip:
    - numpy==1.14.2
    - matplotlib==2.2.2
    - pandas==0.22.0
    - seaborn==0.8.1
    - scikit-learn==0.18.1
    - ipykernel==4.8.2
    - ipython==6.3.0
    - SQLAlchemy==1.2.7
    - xlrd==1.1.0
